[package]
name = "OidosReverb"
version = "2.1.0"
authors = ["Aske Simon Christensen <blueberry@loonies.dk>"]

[dependencies]
vst2 = { git = "https://github.com/askeksa/rust-vst2" }

[lib]
name = "OidosReverb"
crate-type = ["cdylib"]
