[package]
name = "Oidos"
version = "0.1.0"
authors = ["Aske Simon Christensen <blueberry@loonies.dk>"]

[dependencies]
vst2 = { path = "../../rust-vst2" }
#vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2.git" }

[lib]
name = "Oidos"
crate-type = ["dylib"]
