[package]
name = "Oidos"
version = "0.1.0"
authors = ["Aske Simon Christensen <blueberry@loonies.dk>"]
build = "build.rs"

[dependencies]
vst2 = { path = "../../rust-vst2" }
#vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2.git" }
rand = "0.3"

[build-dependencies]
nasm-rs = { git = "https://github.com/askeksa/nasm-rs" }

[lib]
name = "Oidos"
crate-type = ["dylib"]
